# -*- mode: ruby -*-
# vi: set ft=ruby :

# vagrant version 2
Vagrant.configure("2") do |config|
  # ubuntu box
  config.vm.box = "minimal/xenial64"
  config.vm.network "private_network", ip: "192.168.50.4"

  # disable private key replacement so ansible can login
  config.ssh.insert_key = false

  ## ansible configuration
  config.vm.provision "ansible_local" do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.verbose = "v"
    ansible.playbook = "playbook.yml"
  end
end

